# Generated by Django 5.2.4 on 2025-09-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
