# Generated by Django 5.0.6 on 2025-10-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(blank=True, choices=[('password_reset', 'Password Reset'), ('login', 'Login'), ('logout', 'Logout'), ('oauth_login', 'OAuth Login')], max_length=50, null=True),
        ),
    ]
