# Generated by Django 5.0.6 on 2025-11-05 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_profile_image'),
        ('authentication', '0008_account_deletion_feedback'),
    ]

    operations = [
    ]
