# Generated by Django 5.0.6 on 2025-11-16 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_notificationpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Expo Push Token (ExponentPushToken[...])', max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, help_text='Optional device identifier', max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this token is valid and active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time a notification was sent to this token', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Token',
                'verbose_name_plural': 'Push Tokens',
                'db_table': 'push_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pushtoken',
            index=models.Index(fields=['user', 'is_active'], name='push_tokens_user_id_is_active_idx'),
        ),
    ]
