"""
Apple OAuth Service for handling Apple Sign-In authentication.

This service provides secure token verification with nonce-based replay protection
following Apple's Sign in with Apple guidelines.
"""

import os
import hashlib
import jwt
import requests
from jwt.algorithms import RSAAlgorithm
from datetime import datetime, timedelta
from dotenv import load_dotenv

load_dotenv()


class AppleOAuthService:
    """Service for handling Apple OAuth authentication with nonce verification."""
    
    APPLE_KEYS_URL = "https://appleid.apple.com/auth/keys"
    APPLE_ISSUER = "https://appleid.apple.com"
    KEYS_CACHE_TTL = timedelta(hours=24)
    
    _keys_cache = None
    _keys_cached_at = None
    
    @classmethod
    def get_apple_public_keys(cls) -> dict:
        """
        Fetch Apple's public keys (JWKS) for token verification.
        Keys are cached for 24 hours to reduce API calls.
        
        Returns:
            dict: JWKS containing Apple's public keys
            
        Raises:
            ValueError: If unable to fetch keys from Apple
        """
        now = datetime.utcnow()
        if cls._keys_cache and cls._keys_cached_at:
            if now - cls._keys_cached_at < cls.KEYS_CACHE_TTL:
                return cls._keys_cache
        
        try:
            response = requests.get(cls.APPLE_KEYS_URL, timeout=10)
            response.raise_for_status()
            cls._keys_cache = response.json()
            cls._keys_cached_at = now
            return cls._keys_cache
        except requests.RequestException as e:
            raise ValueError(f"Failed to fetch Apple public keys: {str(e)}")

    @staticmethod
    def verify_identity_token(token: str, nonce: str) -> dict:
        """
        Verify Apple identity token signature, claims, and nonce.
        
        This method performs comprehensive token validation:
        1. Fetches Apple's public keys (JWKS)
        2. Verifies JWT signature using RS256 algorithm
        3. Validates issuer is "https://appleid.apple.com"
        4. Validates audience matches configured APPLE_BUNDLE_ID
        5. Validates token has not expired
        6. Verifies nonce claim matches SHA256 hash of provided raw nonce
        
        Args:
            token (str): Apple's identity JWT from Sign in with Apple
            nonce (str): Raw (unhashed) nonce generated by frontend
            
        Returns:
            dict: Verified user data containing:
                - sub: Apple's unique, stable user identifier
                - email: User's email (may be Apple's private relay address)
                - email_verified: Boolean indicating if email is verified
                - nonce: The nonce hash from the token (for audit purposes)
                
        Raises:
            ValueError: If token is invalid, with specific error message:
                - "Invalid token signature" - Signature verification failed
                - "Invalid token issuer" - iss claim doesn't match Apple
                - "Invalid token audience" - aud claim doesn't match Bundle ID
                - "Token has expired" - exp claim is in the past
                - "Invalid nonce" - nonce claim doesn't match SHA256(raw_nonce)
                - "Email not found in token" - Required email claim missing
        """
        try:
            bundle_id = os.getenv('APPLE_BUNDLE_ID')
            if not bundle_id:
                raise ValueError("APPLE_BUNDLE_ID not configured")
            
            # Get Apple's public keys
            keys = AppleOAuthService.get_apple_public_keys()
            
            # Decode header to get key ID
            unverified_header = jwt.get_unverified_header(token)
            kid = unverified_header.get('kid')
            
            if not kid:
                raise ValueError("Token header missing key ID (kid)")
            
            # Find matching key
            public_key = None
            for key in keys.get('keys', []):
                if key.get('kid') == kid:
                    public_key = RSAAlgorithm.from_jwk(key)
                    break
            
            if not public_key:
                raise ValueError("Unable to find matching Apple public key")
            
            # Verify and decode token
            payload = jwt.decode(
                token,
                public_key,
                algorithms=['RS256'],
                audience=bundle_id,
                issuer=AppleOAuthService.APPLE_ISSUER
            )
            
            # Verify nonce: SHA256(raw_nonce) must equal token's nonce claim
            expected_nonce_hash = hashlib.sha256(nonce.encode()).hexdigest()
            token_nonce = payload.get('nonce')
            
            if not token_nonce or token_nonce != expected_nonce_hash:
                raise ValueError("Invalid nonce - possible replay attack")
            
            # Extract user data
            user_data = {
                'sub': payload.get('sub'),
                'email': payload.get('email'),
                'email_verified': payload.get('email_verified', False),
                'nonce': token_nonce,
            }
            
            if not user_data['sub']:
                raise ValueError("User identifier (sub) not found in token")
            
            return user_data
            
        except jwt.ExpiredSignatureError:
            raise ValueError("Token has expired")
        except jwt.InvalidAudienceError:
            raise ValueError("Invalid token audience")
        except jwt.InvalidIssuerError:
            raise ValueError("Invalid token issuer")
        except jwt.InvalidSignatureError:
            raise ValueError("Invalid token signature")
        except ValueError:
            # Re-raise ValueError as-is
            raise
        except Exception as e:
            raise ValueError(f"Token verification failed: {str(e)}")
