# Generated by Django 5.2.4 on 2025-08-20 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_orderno_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderno',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='user.addressmodel'),
        ),
    ]
