# Generated by Django 5.2.6 on 2025-10-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_orderno_images'),
        ('inventory', '0003_orderno_address'),
    ]

    operations = [
    ]
