# Generated by Django 5.0.6 on 2025-10-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_merge_0002_orderno_images_0003_orderno_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderno',
            name='redeemed_referral_bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
