# Generated by Django 5.0.6 on 2025-11-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_orderno_redeemed_referral_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderno',
            name='estimated_order_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
