# Generated by Django 5.0.6 on 2025-11-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_orderno_estimated_order_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to category image stored in S3', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to product image stored in S3', max_length=500, null=True),
        ),
    ]
