/**
 * client/src/app/tracking/[orderId]/payment.tsx
 *
 * Customer Payment Confirmation Screen.
 *
 * This screen is reached AFTER the customer accepts a quote on the quote.tsx screen.
 * It polls the server-authoritative payment state and shows the correct UI based on
 * the BookingPaymentTransaction.status state machine.
 *
 * STATE MACHINE (driven by server, never client-guessed):
 *   payment_ready              → QR is live (UPI) or "waiting for vendor to hand cash"
 *   payment_initiated          → QR shown, vendor scanned
 *   vendor_reference_submitted → Vendor submitted UTR, customer must confirm
 *   customer_confirmation_pending → same as above (alias)
 *   paid / cash_paid           → DONE → navigate to order detail
 *   disputed                   → Dispute recorded, admin will review
 *
 * SECURITY: Amount is ALWAYS shown from server (tx.amount). Never from client state.
 * QR payload is ALWAYS generated by server. Client displays, never generates.
 */

import React, { useCallback, useEffect, useRef, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  RefreshControl,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { ArrowLeft, CheckCircle2, AlertCircle, RefreshCcw } from 'lucide-react-native';
import { AuthService } from '../../../api/apiService';
import { useTheme } from '../../../context/ThemeContext';

const POLL_INTERVAL_MS = 6_000; // 6 s
const formatAmount = (v: number | string) => `₹${Number(v || 0).toFixed(2)}`;

export default function CustomerPaymentScreen() {
  const router = useRouter();
  const { orderId } = useLocalSearchParams<{ orderId: string }>();
  const { colors, isDark } = useTheme();
  const parsedOrderId = Number(orderId);

  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [txData, setTxData] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);

  // Confirmation UI state
  const [confirming, setConfirming] = useState(false);
  const [showDisputeInput, setShowDisputeInput] = useState(false);
  const [disputeReason, setDisputeReason] = useState('');

  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const loadPaymentState = useCallback(async (isRefresh = false) => {
    if (!Number.isFinite(parsedOrderId)) {
      setError('Invalid order ID');
      setLoading(false);
      return;
    }
    if (isRefresh) setRefreshing(true);
    try {
      const data = await AuthService.getOrderPaymentState(parsedOrderId);
      setTxData(data?.payment_transaction ?? null);
      setError(null);
    } catch (err: any) {
      if (!isRefresh) setError(err.message || 'Unable to load payment state');
    } finally {
      setLoading(false);
      if (isRefresh) setRefreshing(false);
    }
  }, [parsedOrderId]);

  useEffect(() => {
    void loadPaymentState();
    pollRef.current = setInterval(() => void loadPaymentState(), POLL_INTERVAL_MS);
    return () => { if (pollRef.current) clearInterval(pollRef.current); };
  }, [loadPaymentState]);

  // Auto-navigate on terminal success
  useEffect(() => {
    if (txData?.status === 'paid' || txData?.status === 'cash_paid') {
      if (pollRef.current) clearInterval(pollRef.current);
      // Short delay so user sees success
      const t = setTimeout(() => {
        router.replace(`/profile/orders/${parsedOrderId}` as any);
      }, 2500);
      return () => clearTimeout(t);
    }
  }, [txData?.status, parsedOrderId, router]);

  const handleConfirm = async (confirmed: boolean) => {
    if (confirming) return;
    if (!confirmed && (!disputeReason.trim() || disputeReason.trim().length < 5)) {
      Alert.alert('Reason required', 'Please briefly describe the issue before disputing.');
      return;
    }
    setConfirming(true);
    try {
      const result = await AuthService.confirmPaymentReceipt(
        parsedOrderId,
        confirmed,
        confirmed ? undefined : disputeReason.trim(),
      );
      setTxData(result?.payment_transaction ?? txData);
      if (confirmed) {
        // Success — let the auto-navigate useEffect handle navigation
      } else {
        Alert.alert(
          'Dispute recorded',
          'Our team will review and contact you within 24 hours.',
        );
      }
    } catch (err: any) {
      Alert.alert('Error', err?.message || 'Please try again.');
    } finally {
      setConfirming(false);
    }
  };

  // ── Loading ──────────────────────────────────────────────────────────────
  if (loading) {
    return (
      <View style={[styles.centered, { backgroundColor: colors.background }]}>
        <ActivityIndicator size="large" color="#ff5b14" />
        <Text style={[styles.subText, { color: colors.textSecondary, marginTop: 12 }]}>
          Loading payment status…
        </Text>
      </View>
    );
  }

  if (error) {
    return (
      <View style={[styles.centered, { backgroundColor: colors.background }]}>
        <AlertCircle size={40} color="#dc2626" />
        <Text style={[styles.errorText, { color: colors.text, marginTop: 12 }]}>{error}</Text>
        <TouchableOpacity
          style={[styles.actionBtn, { backgroundColor: '#ff5b14', marginTop: 16 }]}
          onPress={() => void loadPaymentState()}
        >
          <Text style={styles.actionBtnText}>Retry</Text>
        </TouchableOpacity>
      </View>
    );
  }

  if (!txData) {
    return (
      <View style={[styles.centered, { backgroundColor: colors.background }]}>
        <Text style={[styles.subText, { color: colors.textSecondary }]}>
          No payment transaction found. The vendor may still be processing your quote.
        </Text>
        <TouchableOpacity style={[styles.actionBtn, { backgroundColor: '#ff5b14', marginTop: 16 }]} onPress={() => router.back()}>
          <Text style={styles.actionBtnText}>Go Back</Text>
        </TouchableOpacity>
      </View>
    );
  }

  const txStatus: string = txData.status ?? '';
  const amount: number = Number(txData.amount ?? 0);
  const isUpi = (txData.preferred_payment_method === 'upi') && !txData.cash_fallback_used;
  const isCash = (txData.preferred_payment_method === 'cash') || txData.cash_fallback_used;
  const awaitingConfirmation = txStatus === 'customer_confirmation_pending' || txStatus === 'vendor_reference_submitted';
  const isComplete = txStatus === 'paid' || txStatus === 'cash_paid';
  const isDisputed = txStatus === 'disputed';

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      {/* Header */}
      <View style={[styles.header, { backgroundColor: colors.surface }]}>
        <TouchableOpacity style={styles.backBtn} onPress={() => router.back()} hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}>
          <ArrowLeft size={20} color={colors.text} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: colors.text }]}>Payment Status</Text>
        <TouchableOpacity onPress={() => void loadPaymentState(true)} disabled={refreshing}>
          {refreshing
            ? <ActivityIndicator size="small" color="#ff5b14" />
            : <RefreshCcw size={18} color={colors.textSecondary} />}
        </TouchableOpacity>
      </View>

      <ScrollView
        contentContainerStyle={styles.content}
        refreshControl={
          <RefreshControl refreshing={refreshing} onRefresh={() => void loadPaymentState(true)} tintColor="#ff5b14" colors={['#ff5b14']} />
        }
      >
        {/* ── Amount card ── */}
        <View style={[styles.amountCard, { backgroundColor: colors.surface }]}>
          <Text style={[styles.amountLabel, { color: colors.textSecondary }]}>Payout Amount</Text>
          <Text style={[styles.amountValue, { color: '#ff5b14' }]}>{formatAmount(amount)}</Text>
          <View style={styles.methodRow}>
            <View style={[styles.methodPill, { backgroundColor: isUpi ? '#e8f4fd' : '#e8fdf1' }]}>
              <Text style={[styles.methodPillText, { color: isUpi ? '#0369a1' : '#166534' }]}>
                {isUpi ? '📱 UPI' : '💵 Cash'}
                {txData.cash_fallback_used ? ' (fallback)' : ''}
              </Text>
            </View>
            <StatusPill status={txStatus} />
          </View>
        </View>

        {/* ── QR display (UPI, payment_ready or payment_initiated) ── */}
        {isUpi && (txStatus === 'payment_ready' || txStatus === 'payment_initiated') && txData.upi_qr_payload && (
          <View style={[styles.card, { backgroundColor: colors.surface }]}>
            <Text style={[styles.cardTitle, { color: colors.text }]}>Your UPI QR Code</Text>
            <Text style={[styles.cardSubtitle, { color: colors.textSecondary }]}>
              Ask the vendor to scan this QR code from any UPI app to pay you {formatAmount(amount)}.
              The amount is fixed by the server.
            </Text>
            <QRDisplay payload={txData.upi_qr_payload} amount={amount} upiVpa={txData.customer_upi_vpa_masked} />
          </View>
        )}

        {/* ── Cash: waiting for vendor to hand over ── */}
        {isCash && txStatus === 'payment_ready' && (
          <View style={[styles.card, { backgroundColor: colors.surface }]}>
            <Text style={[styles.cardTitle, { color: colors.text }]}>Cash Payout</Text>
            <Text style={[styles.cardSubtitle, { color: colors.textSecondary }]}>
              The vendor will hand you {formatAmount(amount)} in cash before leaving.
              Once they confirm handover, you will receive a confirmation request.
            </Text>
            <View style={[styles.waitingIndicator, { backgroundColor: isDark ? '#1e3a2a' : '#f0fdf4' }]}>
              <ActivityIndicator size="small" color="#16a34a" />
              <Text style={[styles.waitingText, { color: '#16a34a' }]}>Waiting for vendor to hand over cash…</Text>
            </View>
          </View>
        )}

        {/* ── Awaiting customer confirmation ── */}
        {awaitingConfirmation && (
          <View style={[styles.card, { backgroundColor: colors.surface }]}>
            <Text style={[styles.cardTitle, { color: colors.text }]}>Did you receive the payment?</Text>
            <Text style={[styles.cardSubtitle, { color: colors.textSecondary }]}>
              {isUpi
                ? `Vendor submitted a UPI reference. If ${formatAmount(amount)} appeared in your UPI wallet, confirm below.`
                : `Vendor says they handed you ${formatAmount(amount)} cash. Please confirm.`}
            </Text>

            {isUpi && txData.upi_reference ? (
              <View style={[styles.referenceBox, { backgroundColor: isDark ? '#1e293b' : '#f8fafc' }]}>
                <Text style={[styles.refLabel, { color: colors.textSecondary }]}>UTR / Reference</Text>
                <Text style={[styles.refValue, { color: colors.text }]}>{txData.upi_reference}</Text>
              </View>
            ) : null}

            {!showDisputeInput && (
              <View style={styles.confirmRow}>
                <TouchableOpacity
                  style={[styles.confirmBtn, styles.confirmBtnYes, confirming && styles.disabled]}
                  onPress={() => void handleConfirm(true)}
                  disabled={confirming}
                >
                  {confirming
                    ? <ActivityIndicator color="#fff" size="small" />
                    : <Text style={styles.confirmBtnText}>✓ Yes, I received it</Text>}
                </TouchableOpacity>
                <TouchableOpacity
                  style={[styles.confirmBtn, styles.confirmBtnNo]}
                  onPress={() => setShowDisputeInput(true)}
                  disabled={confirming}
                >
                  <Text style={[styles.confirmBtnText, { color: '#dc2626' }]}>✕ I didn't receive it</Text>
                </TouchableOpacity>
              </View>
            )}

            {showDisputeInput && (
              <View style={styles.disputeSection}>
                <Text style={[styles.cardSubtitle, { color: colors.text, marginBottom: 8 }]}>
                  Please describe the issue:
                </Text>
                <TextInput
                  value={disputeReason}
                  onChangeText={setDisputeReason}
                  placeholder="e.g. Vendor left without paying"
                  placeholderTextColor={colors.textSecondary}
                  multiline
                  numberOfLines={3}
                  style={[styles.disputeInput, { borderColor: colors.border, color: colors.text }]}
                />
                <View style={styles.confirmRow}>
                  <TouchableOpacity
                    style={[styles.confirmBtn, styles.confirmBtnNo, confirming && styles.disabled]}
                    onPress={() => void handleConfirm(false)}
                    disabled={confirming}
                  >
                    {confirming
                      ? <ActivityIndicator color="#dc2626" size="small" />
                      : <Text style={[styles.confirmBtnText, { color: '#dc2626' }]}>Submit Dispute</Text>}
                  </TouchableOpacity>
                  <TouchableOpacity
                    style={[styles.confirmBtn, { borderColor: colors.border }]}
                    onPress={() => setShowDisputeInput(false)}
                  >
                    <Text style={[styles.confirmBtnText, { color: colors.text }]}>Cancel</Text>
                  </TouchableOpacity>
                </View>
              </View>
            )}
          </View>
        )}

        {/* ── Success ── */}
        {isComplete && (
          <View style={[styles.card, { backgroundColor: '#dcfce7', borderColor: '#86efac', borderWidth: 1 }]}>
            <View style={styles.completedRow}>
              <CheckCircle2 size={28} color="#16a34a" />
              <Text style={[styles.cardTitle, { color: '#14532d', marginLeft: 10 }]}>Payment Confirmed!</Text>
            </View>
            <Text style={[styles.cardSubtitle, { color: '#166534' }]}>
              {formatAmount(amount)} received. Your pickup is complete.
            </Text>
            <ActivityIndicator size="small" color="#16a34a" style={{ marginTop: 10 }} />
            <Text style={[styles.subText, { color: '#166534', marginTop: 6 }]}>Redirecting to your order…</Text>
          </View>
        )}

        {/* ── Disputed ── */}
        {isDisputed && (
          <View style={[styles.card, { backgroundColor: '#fef2f2', borderColor: '#fca5a5', borderWidth: 1 }]}>
            <View style={styles.completedRow}>
              <AlertCircle size={28} color="#dc2626" />
              <Text style={[styles.cardTitle, { color: '#991b1b', marginLeft: 10 }]}>Payment Disputed</Text>
            </View>
            <Text style={[styles.cardSubtitle, { color: '#7f1d1d' }]}>
              Your dispute has been recorded. Our team will review and contact you within 24 hours.
            </Text>
            {txData.dispute_reason ? (
              <Text style={[styles.subText, { color: '#991b1b', marginTop: 8 }]}>
                Your reason: "{txData.dispute_reason}"
              </Text>
            ) : null}
          </View>
        )}

        {/* ── Live polling indicator ── */}
        {!isComplete && !isDisputed && (
          <View style={styles.pollingRow}>
            <View style={styles.pulseDot} />
            <Text style={[styles.subText, { color: colors.textSecondary }]}>
              Auto-refreshing every {POLL_INTERVAL_MS / 1000}s
            </Text>
          </View>
        )}
      </ScrollView>
    </View>
  );
}

// ── QR Display component ─────────────────────────────────────────────────────
// Uses expo-barcode-generator or a simple react-native-qrcode-svg if installed.
// Gracefully falls back to showing the raw UPI URI if QR lib unavailable.

function QRDisplay({ payload, amount, upiVpa }: { payload: string; amount: number; upiVpa: string }) {
  const [qrAvailable, setQrAvailable] = useState<boolean | null>(null);
  const [QRCode, setQRCode] = useState<any>(null);

  useEffect(() => {
    try {
      // Try to import react-native-qrcode-svg (may not be installed yet)
      const mod = require('react-native-qrcode-svg');
      setQRCode(() => mod.default ?? mod.QRCode ?? null);
      setQrAvailable(true);
    } catch {
      setQrAvailable(false);
    }
  }, []);

  if (qrAvailable === null) {
    return <ActivityIndicator color="#ff5b14" style={{ marginVertical: 24 }} />;
  }

  if (qrAvailable && QRCode) {
    return (
      <View style={qrStyles.container}>
        <QRCode value={payload} size={220} />
        <Text style={qrStyles.caption}>
          Scan with any UPI app • {formatAmount(amount)} to {upiVpa}
        </Text>
      </View>
    );
  }

  // Fallback: display raw URI
  return (
    <View style={qrStyles.fallback}>
      <Text style={qrStyles.fallbackLabel}>UPI Payment URI</Text>
      <Text style={qrStyles.fallbackUri} selectable>{payload}</Text>
      <Text style={qrStyles.caption}>Amount: {formatAmount(amount)} • To: {upiVpa}</Text>
      <Text style={qrStyles.installNote}>
        Install react-native-qrcode-svg to show QR code
      </Text>
    </View>
  );
}

// ── Status pill ──────────────────────────────────────────────────────────────
const STATUS_META: Record<string, { label: string; color: string; bg: string }> = {
  pending:                       { label: 'Pending',            color: '#92400e', bg: '#fef3c7' },
  customer_details_required:     { label: 'Waiting for you',    color: '#92400e', bg: '#fef3c7' },
  payment_ready:                 { label: 'Ready',              color: '#065f46', bg: '#d1fae5' },
  payment_initiated:             { label: 'In Progress',        color: '#1e40af', bg: '#dbeafe' },
  vendor_reference_submitted:    { label: 'Confirm Receipt',    color: '#92400e', bg: '#fef3c7' },
  customer_confirmation_pending: { label: 'Confirm Receipt',    color: '#92400e', bg: '#fef3c7' },
  paid:                          { label: 'Paid ✓',             color: '#14532d', bg: '#dcfce7' },
  cash_paid:                     { label: 'Cash Paid ✓',        color: '#14532d', bg: '#dcfce7' },
  disputed:                      { label: 'Disputed',           color: '#991b1b', bg: '#fef2f2' },
  failed:                        { label: 'Failed',             color: '#991b1b', bg: '#fef2f2' },
  cancelled:                     { label: 'Cancelled',          color: '#6b7280', bg: '#f3f4f6' },
};

function StatusPill({ status }: { status: string }) {
  const meta = STATUS_META[status] ?? { label: status, color: '#6b7280', bg: '#f3f4f6' };
  return (
    <View style={[pillStyles.pill, { backgroundColor: meta.bg }]}>
      <Text style={[pillStyles.text, { color: meta.color }]}>{meta.label}</Text>
    </View>
  );
}

const pillStyles = StyleSheet.create({
  pill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  text: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
});

const qrStyles = StyleSheet.create({
  container: {
    alignItems: 'center',
    paddingVertical: 16,
    gap: 12,
  },
  caption: {
    fontSize: 12,
    color: '#475569',
    textAlign: 'center',
  },
  fallback: {
    padding: 14,
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    marginTop: 12,
    gap: 6,
  },
  fallbackLabel: {
    fontWeight: '700',
    color: '#0f172a',
    fontSize: 13,
  },
  fallbackUri: {
    fontSize: 11,
    color: '#0369a1',
    fontFamily: 'monospace',
  },
  installNote: {
    fontSize: 11,
    color: '#94a3b8',
    marginTop: 4,
  },
});

const styles = StyleSheet.create({
  container: { flex: 1 },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingTop: 52,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.06)',
  },
  backBtn: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: { fontSize: 17, fontWeight: '700' },
  content: { padding: 16, gap: 14, paddingBottom: 40 },
  errorText: { fontSize: 15, fontWeight: '600', textAlign: 'center', marginBottom: 8 },
  subText: { fontSize: 12, textAlign: 'center' },

  // Amount card
  amountCard: {
    borderRadius: 20,
    padding: 18,
    alignItems: 'center',
    gap: 8,
  },
  amountLabel: { fontSize: 13, fontWeight: '600' },
  amountValue: { fontSize: 36, fontWeight: '900', letterSpacing: -0.5 },
  methodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  methodPill: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
  },
  methodPillText: { fontWeight: '700', fontSize: 12 },

  // Generic card
  card: {
    borderRadius: 18,
    padding: 16,
    gap: 10,
  },
  cardTitle: { fontSize: 16, fontWeight: '800' },
  cardSubtitle: { fontSize: 13, lineHeight: 19 },

  // Waiting
  waitingIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 12,
    padding: 12,
  },
  waitingText: { fontSize: 13, fontWeight: '600' },

  // Reference box
  referenceBox: {
    borderRadius: 10,
    padding: 12,
    gap: 2,
  },
  refLabel: { fontSize: 10, fontWeight: '700', letterSpacing: 0.5, textTransform: 'uppercase' },
  refValue: { fontSize: 15, fontWeight: '700', fontFamily: 'monospace' },

  // Confirm buttons
  confirmRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  confirmBtn: {
    flex: 1,
    minHeight: 46,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  confirmBtnYes: {
    backgroundColor: '#16a34a',
  },
  confirmBtnNo: {
    borderColor: '#dc2626',
    backgroundColor: 'transparent',
  },
  confirmBtnText: { fontWeight: '700', fontSize: 13, color: '#fff' },

  // Dispute
  disputeSection: { gap: 8 },
  disputeInput: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    minHeight: 72,
    textAlignVertical: 'top',
  },

  // Complete / disputed
  completedRow: { flexDirection: 'row', alignItems: 'center' },

  // Polling
  pollingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 6,
  },
  pulseDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#22c55e',
  },

  // Action buttons
  actionBtn: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionBtnText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  disabled: { opacity: 0.5 },
});
